# Generated by Django 5.0.7 on 2025-10-25 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, help_text='SES message ID', max_length=255, unique=True)),
                ('subject', models.CharField(max_length=500)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(db_index=True, max_length=254)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('failed', 'Failed'), ('complained', 'Complained')], db_index=True, default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='contacts.contact')),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('send', 'Send'), ('delivery', 'Delivery'), ('bounce', 'Bounce'), ('complaint', 'Complaint'), ('open', 'Open'), ('click', 'Click'), ('reject', 'Reject')], db_index=True, max_length=20)),
                ('bounce_type', models.CharField(blank=True, choices=[('hard', 'Hard Bounce'), ('soft', 'Soft Bounce')], max_length=10, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data from SES')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.emaillog')),
            ],
            options={
                'db_table': 'email_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['message_id'], name='email_logs_message_367807_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status'], name='email_logs_status_e3be55_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['to_email'], name='email_logs_to_emai_9c46ac_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['created_at'], name='email_logs_created_76afc3_idx'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['event_type'], name='email_event_event_t_4388f0_idx'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['timestamp'], name='email_event_timesta_4bf916_idx'),
        ),
    ]
