# Generated by Django 5.0.7 on 2025-10-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subject_template', models.CharField(max_length=500)),
                ('html_content', models.TextField()),
                ('plain_text_content', models.TextField()),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Available variables: {name, email, custom_fields}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
