# Generated by Django 5.0.7 on 2025-10-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='design_json',
            field=models.JSONField(blank=True, help_text='Unlayer email editor design JSON', null=True),
        ),
    ]
