# Generated by Django 5.0.7 on 2025-10-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('total_contacts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('is_subscribed', models.BooleanField(default=True)),
                ('is_suppressed', models.BooleanField(db_index=True, default=False, help_text='Suppressed due to bounces or complaints')),
                ('suppression_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lists', models.ManyToManyField(blank=True, related_name='contacts', to='contacts.contactlist')),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='contacts_email_2eb381_idx'), models.Index(fields=['is_subscribed'], name='contacts_is_subs_ba3579_idx'), models.Index(fields=['is_suppressed'], name='contacts_is_supp_ac2da3_idx')],
            },
        ),
    ]
